# -*- coding: utf-8 -*-
"""「week6_demo.ipynb」的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bsdxi2FDNvMTLlwAgRBXyqzMnMQx2O6b

# Matplotlib基本練習

# 1.繪製簡單的折線圖
"""

# 請在"填空"處，輸入所需要的指令或參數

import pandas as pd
import matplotlib.pyplot as plt

products = {"分類": ["居家","居家","娛樂","娛樂","科技","科技"],
       "商店": ["家樂福A","大潤發A","家樂福B","全聯超A","大潤發B","家樂福C"],
       "價格": [11.42,23.50,19.99,15.95,55.75,111.55]}

df = pd.DataFrame(products, columns = ["分類", "商店", "價格"])
df["價格"].plot(kind="line") # 繪製折線圖
plt.grid(1) # 顯示圖表的格線

# Colab 進行matplotlib繪圖時顯示繁體中文
# 下載台北思源黑體並命名taipei_sans_tc_beta.ttf，移至指定路徑
!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager

fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
mpl.rc('font', family='Taipei Sans TC Beta')

"""# 2.顯示x軸和y軸的說明標籤"""

# 請在"填空"處，輸入所需要的指令或參數
# Line 3-12行請複製上一題3-12行的解答
import pandas as pd
import matplotlib.pyplot as plt

products = {"分類": ["居家","居家","娛樂","娛樂","科技","科技"],
       "商店": ["家樂福A","大潤發A","家樂福B","全聯超A","大潤發B","家樂福C"],
       "價格": [11.42,23.50,19.99,15.95,55.75,111.55]}

df = pd.DataFrame(products, columns = ["分類", "商店", "價格"])
df["價格"].plot(kind="line") # 繪製折線圖
plt.grid(1) # 顯示圖表的格線

plt.xticks([0, 1, 2, 3, 4, 5], df["商店"])
plt.xlabel("商店名稱")
plt.ylabel("價格")

"""# 3.請繪製水平長條圖"""

# 請在"填空"處，輸入所需要的指令或參數
# Line 3-18行請複製上一題3-18行的解答
import pandas as pd
import matplotlib.pyplot as plt

products = {"分類": ["居家","居家","娛樂","娛樂","科技","科技"],
       "商店": ["家樂福A","大潤發A","家樂福B","全聯超A","大潤發B","家樂福C"],
       "價格": [11.42,23.50,19.99,15.95,55.75,111.55]}

df = pd.DataFrame(products, columns = ["分類", "商店", "價格"])
df["價格"].plot(kind="barh") # 繪製折線圖
plt.grid(1) # 顯示圖表的格線

#plt.xticks([0, 1, 2, 3, 4, 5], df["價格"])
plt.ylabel("商店名稱")
plt.xlabel("價格")



# 延伸上一題相同內容
# 水平長條圖 (X軸是價格金額，Y軸是商店名稱)
plt.yticks([0, 1, 2, 3, 4, 5], df["商店"])

"""# 4.請繪製派圖"""

# 請在"填空"處，輸入所需要的指令或參數
# Line 3-22行請複製上一題3-22行的解答
import pandas as pd
import matplotlib.pyplot as plt

products = {"分類": ["居家","居家","娛樂","娛樂","科技","科技"],
       "商店": ["家樂福A","大潤發A","家樂福B","全聯超A","大潤發B","家樂福C"],
       "價格": [11.42,23.50,19.99,15.95,55.75,111.55]}

df = pd.DataFrame(products, columns = ["分類", "商店", "價格"])
#df["價格"].plot(kind="barh") # 繪製折線圖
#plt.grid(1) # 顯示圖表的格線

#plt.xticks([0, 1, 2, 3, 4, 5], df["價格"])
#plt.ylabel("商店名稱")
#plt.xlabel("價格")



# 延伸上一題相同內容
# 水平長條圖 (X軸是價格金額，Y軸是商店名稱)
plt.yticks([0, 1, 2, 3, 4, 5], df["商店"])

# 延伸上一題相同內容
# 派圖(groupby 是依據"分類"的數據，標題是商店名稱)
df_grouped = df.groupby("分類")
type = df_grouped["商店"].count()
type.plot(kind="pie", title="商店名稱")
plt.ylabel("")
